FROM golang:1.21-alpine as builder
RUN apk add --no-cache gcc musl-dev
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 go build -a -tags timetzdata -installsuffix cgo -o main .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
ADD https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie /usr/local/bin/aws-lambda-rie
RUN chmod 755 /usr/local/bin/aws-lambda-rie
COPY --from=builder /app/main /main
RUN chmod +x /main

CMD ["/main"]
ENTRYPOINT [ "/usr/local/bin/aws-lambda-rie" ]
